language: python
python:
  - '3.7'
script:
  - echo foot
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  server: $PYPI_SERVER
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    branch: testing